import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {bindVisualAcceptance} from '../src/visual-acceptance.mjs';
import {buildVerdict} from '../src/verdict.mjs';
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
test('different-page pixel metrics cannot substitute for exact reviewed image acceptance',async t=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'theme-lab-visual-acceptance-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));
 const candidate=path.join(dir,'candidate.png'),reference=path.join(dir,'reference.png');
 await fs.writeFile(candidate,'candidate pixels');await fs.writeFile(reference,'different reference content');
 const capture={desktop:{candidate_path:candidate,reference_path:reference,comparison:{status:'fail',normalized_rmse:0.4}}};
 const inputs={css:'theme CSS',wikitext:'JP article'};
 await bindVisualAcceptance(capture,null,inputs);
 assert.equal(buildVerdict({visual:capture}).verdict,'inconclusive');
 const review={schema:'theme_lab_visual_acceptance.v1',candidate_css_sha256:sha(inputs.css),candidate_preview_sha256:sha(inputs.wikitext),viewports:{desktop:{candidate_screenshot_sha256:sha('candidate pixels'),reference_screenshot_sha256:sha('different reference content'),status:'pass',reviewer:'reviewer',reviewed_at:new Date().toISOString(),note:'Reviewed different article content; all controls remain readable.'}}};
 await bindVisualAcceptance(capture,review,inputs);
 assert.equal(buildVerdict({visual:capture}).verdict,'pass');
 assert.equal(buildVerdict({visual:capture,viewports:{mobile:{document_overflow_px:12}}}).verdict,'fail');
 review.viewports.desktop.status='fail';await bindVisualAcceptance(capture,review,inputs);
 assert.equal(buildVerdict({visual:capture}).verdict,'fail');
 await fs.writeFile(candidate,'changed pixels');await bindVisualAcceptance(capture,review,inputs);
 assert.equal(buildVerdict({visual:capture}).verdict,'inconclusive');
 await fs.writeFile(candidate,'candidate pixels');await bindVisualAcceptance(capture,review,{...inputs,css:'changed CSS'});
 assert.equal(buildVerdict({visual:capture}).verdict,'inconclusive');
});
