name: '[backend] Docker build Caddy (prod)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/prod/caddy/*'
      - '.github/workflows/docker-build-caddy.prod.yaml'
      - '.github/workflows/docker-build-template.yaml'

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || (github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'release-certification')) }}
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/caddy
      image-name: caddy
      tier: prod
