name: '[backend] Docker build Framerail (prod)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/prod/framerail/Dockerfile'
      - '.github/workflows/docker-build-framerail.prod.yaml'
      - '.github/workflows/docker-build-template.yaml'

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || (github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'release-certification')) }}
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/framerail
      image-name: framerail
      tier: prod
